"""
Unit tests for .gitignore configuration and repository tracking.

This module tests that processing_time_log.txt is properly ignored
and removed from repository tracking.
"""

import subprocess
import sys
from pathlib import Path

import pytest

# Add parent directory to path to import modules
sys.path.insert(0, str(Path(__file__).parent.parent))


class TestGitignoreConfiguration:
    """Tests for .gitignore configuration"""

    def test_processing_time_log_in_gitignore(self):
        """Test that processing_time_log.txt is in .gitignore"""
        gitignore_path = Path(__file__).parent.parent / ".gitignore"
        assert gitignore_path.exists(), ".gitignore file should exist"

        with open(gitignore_path, "r", encoding="utf-8") as f:
            gitignore_content = f.read()

        # Check that processing_time_log.txt is in .gitignore
        assert "processing_time_log.txt" in gitignore_content, (
            "processing_time_log.txt should be in .gitignore"
        )

    def test_processing_time_log_not_tracked(self):
        """Test that processing_time_log.txt is not tracked by git"""
        # Run git ls-files to check if processing_time_log.txt is tracked
        result = subprocess.run(
            ["git", "ls-files", "processing_time_log.txt"],
            capture_output=True,
            text=True,
            cwd=Path(__file__).parent.parent,
        )

        # If file is tracked, git ls-files will return the file path
        # If not tracked, it will return empty output
        assert result.returncode == 0, "git ls-files should succeed"
        assert (
            "processing_time_log.txt" not in result.stdout
        ), "processing_time_log.txt should not be tracked by git"

    def test_processing_time_log_can_be_generated(self, tmp_path):
        """Test that processing_time_log.txt can still be generated"""
        # Test that the file can be created directly (simulating initialize_processing_time_log)
        log_file = tmp_path / "processing_time_log.txt"
        
        # Create the file with expected content
        with open(log_file, "w", encoding="utf-8") as f:
            f.write("# Processing time log generated by collect_responses.py\n")
        
        # File should be created
        assert log_file.exists(), "processing_time_log.txt should be created"

        # File should have expected content
        with open(log_file, "r", encoding="utf-8") as f:
            content = f.read()
            assert "Processing time log" in content, (
                "File should contain expected header"
            )

